### ISSUE TITLE
block

### ISSUE THREAD

**Issue by nmo0ory** [TeamSpeak-Systems/ts3init_linux_netfilter_module#15]
hello,
in my country the teamspeak is blocked 
not just teamspeak 
most of the VOIP service is stooped like the voice chat in games
is this will make the client login normal ?
or i need something else to let every one join ? 
because now we use VPN

**Comment by nwerensteijn** [comment]
This module is not meant, or able, to connect to blocked servers. VPN's are your best bet for now.
