### ISSUE TITLE
Unable to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by foosinn** [TeamSpeak-Systems/ts3init_linux_netfilter_module#19]
xtables libraries dir has changed from `install: target '/lib/xtables/' is not a directory: No such file or directory
` to `/usr/lib/x86_64-linux-gnu/xtables`.

```
install -g root -o root -m 644 libxt_ts3init.so libxt_ts3init_get_cookie.so libxt_ts3init_get_puzzle.so libxt_TS3INIT_RESET.so libxt_TS3INIT_SET_COOKIE.so libxt_TS3INIT_GET_COOKIE.so /lib/xtables/
install: target '/lib/xtables/' is not a directory: No such file or directory
Makefile.xtables:9: recipe for target 'install' failed
```

**Comment by virsIT** [comment]
Perhaps this option will help, did in Debian Stretch
ln -s /usr/lib/i386-linux-gnu/xtables /lib/xtables

**Comment by foosinn** [comment]
I'm not sure if that's a better solution than supplying the paths directly in the install scripts.

So Ubuntu Bionic and Debian Stretch seem to use either `/usr/lib/x86_64-linux-gnu/xtables` or `/usr/lib/i386-linux-gnu/xtables` instead of `/lib/xtables/`.
